name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: console-calc:latest
          outputs: type=docker,dest=/tmp/console-calc.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: console-calc
          path: /tmp/console-calc.tar
          retention-days: 1
  lint:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Download docker image
        uses: actions/download-artifact@v3
        with:
          name: console-calc
          path: /tmp
      - name: Run Eslint
        run: |
          docker load --input /tmp/console-calc.tar
          docker run console-calc:latest yarn lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Download docker image
        uses: actions/download-artifact@v3
        with:
          name: console-calc
          path: /tmp
      - name: Run Jest
        run: |
          docker load --input /tmp/console-calc.tar
          docker run console-calc:latest yarn test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download docker image
        uses: actions/download-artifact@v3
        with:
          name: console-calc
          path: /tmp
      - name: Run build app
        run: |
          docker load --input /tmp/console-calc.tar
          docker run console-calc:latest yarn build
